name: Create Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Zip File
        run: |
          zip -r my-repo-files.zip .

      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: my-repo-zip
          path: my-repo-files.zip

      - name: Install Packer plugin
        run: packer plugins install github.com/hashicorp/amazon
      

      - name: Building Packer Template
        run: |
          packer build -var "demo_account_id=${{ secrets.DEMO_ACCOUNT_ID }}" \
                       -var "source_ami=${{ secrets.SOURCE_AMI }}" \
                       -var "ami_name=${{ secrets.AMI_NAME }}" \
                       -var "aws_region=${{ secrets.AWS_REGION }}" \
                       -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                       -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
                       debian-ami.pkr.hcl | sudo tee output.txt
          tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' >> ami.txt
     
