name: Create Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Zip File
        run: |
          zip -r my-repo-files.zip .

      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: my-repo-zip
          path: my-repo-files.zip

      - name: Install Packer plugin
        run: |
         packer plugins install github.com/hashicorp/amazon
        if: always()
      
      - name: Run Packer
        run: |
          # Install Packer
          curl -fsSL https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer init debian-ami.pkr.hcl

          # Run Packer build (modify this command as needed)
          packer build -var "demo_account_id=${{ secrets.DEMO_ACCOUNT_ID }}" \
                     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
                     -var "ami_name=${{ secrets.AMI_NAME }}" \
                     -var "vpc_id=${{ secrets.VPC_ID }}" \
                     -var "aws_region=${{ secrets.AWS_REGION }}" \
                     -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY}}" \
                     -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY}}" \
                      debian-ami.pkr.hcl
